T1_301048660/Models/Poco/Car.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace T1_301048660.Models.Poco
{
    public class Car
    {
        public int CarID { get; set; }
        public string LicencePlate { get; set; }
        public string OwnersName { get; set; }
        public string OwnersAddress { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public bool AD4Doors { get; set; }
        public bool ADHybrid { get; set; }
        public bool AD4WD { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}

T1_301048660/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using T1_301048660.Models.Poco;
using T1_301048660.Models.Repositories;
using T1_301048660.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace T1_301048660.Controllers
{
    public class CarController : Controller
    {
        private ICarRepository _carRepository { get; }

        public CarController(ICarRepository carRepository) => _carRepository = carRepository; 

        public IActionResult Index()
        {
            return View(_carRepository.Cars);
        }

        public IActionResult Details(int? id, bool created = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = _carRepository.Get(id.Value);

            if (car == null)
            {
                return NotFound();
            }

            if (created)
            {
                ViewBag.CurrentAction = "Created";
            }

            return View(car);
        }

        public IActionResult Create()
        {
            var car = new CarCreateEditViewModel();
            return View(car);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CarCreateEditViewModel car)
        {
            if (ModelState.IsValid)
            {
                int id = _carRepository.Add(Map(car));
                return RedirectToAction(nameof(Details), new { id, created = true });
            }
            return View(car);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = _carRepository.Get(id.Value);

            if (car == null)
            {
                return NotFound();
            }

            return View(Map(car));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, CarCreateEditViewModel car)
        {
            if (id != car.CarID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _carRepository.Update(Map(car));
                }
                catch (Exception ex)
                {
                    if (!CarExists(car.CarID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = _carRepository.Get(id.Value);

            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            _carRepository.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        private bool CarExists(int id)
        {
            return _carRepository.Cars.Any(e => e.CarID == id);
        }
        private CarCreateEditViewModel Map(Car car)
        {
            return new CarCreateEditViewModel()
            {
                CarID = car.CarID,
                LicencePlate = car.LicencePlate,
                OwnersName = car.OwnersName,
                OwnersAddress = car.OwnersAddress,
                Make = car.Make,
                Model = car.Model,
                AD4Doors = car.AD4Doors,
                AD4WD = car.AD4WD,
                ADHybrid = car.ADHybrid
            };
        }
        private Car Map(CarCreateEditViewModel car)
        {
            return new Car()
            {
                CarID = car.CarID,
                LicencePlate = car.LicencePlate,
                OwnersName = car.OwnersName,
                OwnersAddress = car.OwnersAddress,
                Make = car.Make,
                Model = car.Model,
                AD4Doors = car.AD4Doors,
                AD4WD = car.AD4WD,
                ADHybrid = car.ADHybrid
            };
        }

    }
}

T1_301048660/Views/Shared/Car/CreateEdit.cshtml
@model CarCreateEditViewModel

<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<input type="hidden" asp-for="CarID" />
<div class="form-group">
    <label asp-for="LicencePlate" class="control-label"></label>
    <input asp-for="LicencePlate" class="form-control" />
    <span asp-validation-for="LicencePlate" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="OwnersName" class="control-label"></label>
    <input asp-for="OwnersName" class="form-control" />
    <span asp-validation-for="OwnersName" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="OwnersAddress" class="control-label"></label>
    <input asp-for="OwnersAddress" class="form-control" />
    <span asp-validation-for="OwnersAddress" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="Make" class="control-label"></label>
    <select asp-for="Make" asp-items="Model.Makes" class="form-control" asp-ite></select>
    <span asp-validation-for="Make" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Model" class="control-label"></label>
    <input asp-for="Model" class="form-control" />
    <span asp-validation-for="Model" class="text-danger"></span>
</div>

<div class="form-group">
    <div>
        <label class="control-label">Additional Features</label>

    </div>
    <div class="checkbox-content">
        <div class="checkbox-float">
            <label asp-for="AD4Doors" class="control-label"></label>
            <input asp-for="AD4Doors" class="form-control checkbox" />
            <span asp-validation-for="AD4Doors" class="text-danger"></span>
        </div>
           
        <div class="checkbox-float">
            <label asp-for="ADHybrid" class="control-label"></label>
            <input asp-for="ADHybrid" class="form-control checkbox" />
            <span asp-validation-for="ADHybrid" class="text-danger"></span>

        </div>

        <div class="checkbox-float">
            <label asp-for="AD4WD" class="control-label"></label>
            <input asp-for="AD4WD" class="form-control checkbox" />
            <span asp-validation-for="AD4WD" class="text-danger"></span>
        </div>        
    </div>
</div>

T1_301048660/Views/Shared/Car/DetailsDelete.cshtml
@model Car

<dl class="dl-horizontal">
    <dt>
        @Html.DisplayNameFor(model => model.LicencePlate)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.LicencePlate)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.OwnersAddress)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.OwnersAddress)
    </dd>
    <dt>
        @Html.DisplayNameFor(model => model.OwnersAddress)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.OwnersAddress)
    </dd>
    <dt>
        Created Date
    </dt>
    <dd>
        @Html.DisplayFor(model => model.ModifiedDate)
    </dd>
</dl>

T1_301048660/Views/Shared/Car/List.cshtml
@model IEnumerable<Car>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.OwnersName)
            </th>
          
            <th class="th-controls"></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                <a asp-controller="Car" asp-action="Details" asp-route-id="@item.CarID" class="not-btn">
                    @Html.DisplayFor(modelItem => item.OwnersName)
                </a>
            </td>
          
            <td>
                <a asp-controller="Car" asp-action="Edit" asp-route-id="@item.CarID">Edit</a> |
                <a asp-controller="Car" asp-action="Details" asp-route-id="@item.CarID">Details</a> |
                <a asp-controller="Car" asp-action="Delete" asp-route-id="@item.CarID">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>